# Generated by Django 5.1.1 on 2025-10-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="PressMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("publication", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True)),
                ("published_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Press Mention",
                "verbose_name_plural": "Press Mentions",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="SpeakingEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("meetup", "Meetup"),
                            ("workshop", "Workshop"),
                            ("webinar", "Webinar"),
                            ("podcast", "Podcast"),
                            ("interview", "Interview"),
                        ],
                        default="conference",
                        max_length=50,
                    ),
                ),
                ("slides_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("event_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Speaking Engagement",
                "verbose_name_plural": "Speaking Engagements",
                "ordering": ["-event_date"],
            },
        ),
    ]
